// A mapping of state code strings to state names
export const STATE_CODES = {
  AK: "Alaska",
  AL: "Alabama",
  AR: "Arkansas",
  AS: "American Samoa",
  AZ: "Arizona",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  DC: "District of Columbia",
  "D.C.": "District of Columbia",
  FL: "Florida",
  FM: "Micronesia",
  GA: "Georgia",
  GU: "Guam",
  HI: "Hawaii",
  IA: "Iowa",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  MA: "Massachusetts",
  MD: "Maryland",
  ME: "Maine",
  MH: "Marshall Islands",
  MI: "Michigan",
  MN: "Minnesota",
  MO: "Missouri",
  MP: "Northern Marianas",
  MS: "Mississippi",
  MT: "Montana",
  NC: "North Carolina",
  ND: "North Dakota",
  NE: "Nebraska",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NV: "Nevada",
  NY: "New York",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  PR: "Puerto Rico",
  PW: "Palau",
  RI: "Rhode Island",
  SC: "South Carolina",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VA: "Virginia",
  VI: "Virgin Islands",
  VT: "Vermont",
  WA: "Washington",
  WI: "Wisconsin",
  WV: "West Virginia",
  WY: "Wyoming",
  SD: "South Dakota",
};

// A set (as an object) of US state names
export const STATE_NAMES = {
  Alaska: true,
  Alabama: true,
  Arkansas: true,
  Arizona: true,
  California: true,
  Colorado: true,
  Connecticut: true,
  "District of Columbia": true,
  Delaware: true,
  Florida: true,
  Georgia: true,
  Hawaii: true,
  Iowa: true,
  Idaho: true,
  Illinois: true,
  Indiana: true,
  Kansas: true,
  Kentucky: true,
  Louisiana: true,
  Massachusetts: true,
  Maryland: true,
  Maine: true,
  Michigan: true,
  Minnesota: true,
  Missouri: true,
  Mississippi: true,
  Montana: true,
  "North Carolina": true,
  "North Dakota": true,
  Nebraska: true,
  "New Hampshire": true,
  "New Jersey": true,
  "New Mexico": true,
  Nevada: true,
  "New York": true,
  Ohio: true,
  Oklahoma: true,
  Oregon: true,
  Pennsylvania: true,
  "Rhode Island": true,
  "South Carolina": true,
  Tennessee: true,
  Texas: true,
  Utah: true,
  Virginia: true,
  Vermont: true,
  Washington: true,
  Wisconsin: true,
  "West Virginia": true,
  "South Dakota": true,
};
